# 线上环境
# @author <a href="https://github.com/linhai0872">林海
spring:
  application:
    name: youlin-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.139.58:3306/usermatching
    username: usermatching
    password: MaPC5sMjzXhJSk8j
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    host: 47.106.139.58
    port: 6379
    database: 0
    password: hyx618redis
server:
  port: 8084
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 47.106.139.58
#        domain: localhost # cookie作用域 前后端不同端口 提取前后端的公共地址
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl //mybatis日志输出
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)